spring:
#  application:
#    name: ${project.artifactId}
  #H2 database as default
  datasource: {url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE, platform: h2,
               driver-class-name: org.h2.Driver, username: sa}
  jpa:
    hibernate: {ddl-auto: none}
    database-platform: {org.hibernate.dialect.H2Dialect}
    properties:
      hibernate: { show_sql: true, use_sql_comments: true, format_sql: true}
  h2:
    console:
      enabled: true
      path: /h2-console
#
  resources:
    static-locations: classpath:static
  #######################################################################################
  ##                  Database section
  ## The following section is for database configuration.
  ## The following database are supported: Oracle, MS SQL Server, and PostgreSQL.
  ## Please only use one to avoid startup issues
  #######################################################################################
  ##  PostgreSQL:
  #######################################################################################
#  datasource:
#     url: jdbc:postgresql://localhost:5432/${project.artifactId}
#     driver-class-name: org.postgresql.Driver
#     username: postgres
#     password: password
#     hikari:
#       auto-commit: false
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect


  #######################################################################################
  ##  MySql DataBase Configuration :
  #######################################################################################
#  datasource:
#    url: jdbc:mysql://localhost:3306/${project.artifactId}?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: none


  # Make sure your flyway script observes the following naming convention - <Prefix><Version>__<Description>.sql; ex. V1_0_0__biowagon.sql
  # The version minors/majors must be separated with underscores, while the description part must be separated with two underscores.
  flyway:
    enabled: false


server:
  port: 8700


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.glassfish.jersey: ERROR
    org.reflections: ERROR
    com.hcb.services.configuration: INFO
    org.h2: DEBUG
    org.flywaydb: DEBUG
    com.hcb.services.common.discovery: DEBUG
    com.hcb.services.toolkit: DEBUG
  path: ${user.home}/hcb/services/${spring.application.name}/logs
  file: ${logging.path}/${spring.application.name}.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight{[%-5level]} %X{CORRELATION_ID} %X{TENANT}:%X{USER} %X{SERVICE} %style{[%t]}{magenta} %style{%c:%M}{cyan} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %X{CORRELATION_ID} %X{TENANT}:%X{USER} [%t] %c:%M - %msg%n'